export default {
  CHANGE_COLOR: 'CHANGE_COLOR',
  NO_SUCH_ARTIST: 'NO_SUCH_ARTIST',
  UPDATE_ARTIST_ID:'UPDATE_ARTIST_ID',
  SEARCH_TOKEN:'SEARCH_TOKEN',
  SET_COUNTRY:'SET_COUNTRY',
  UPDATE_TOKEN:'UPDATE_TOKEN'
}
